#配置合适的yaml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Dept
    username: root
    password: '051022'
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置日志
logging:
  level:
    org.mybatis: DEBUG

#配置mybatis
mybatis:
  type-aliases-package: com.yj.pojo
  mapper-locations: classpath:mapper/*.xml
